-- Run once in Supabase Dashboard > SQL Editor. Uses only user-scoped RLS policies.
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,display_name text not null check(char_length(display_name) between 2 and 20),account_level int not null default 1,account_xp bigint not null default 0,gold bigint not null default 0 check(gold>=0),gems bigint not null default 0 check(gems>=0),keys int not null default 0 check(keys>=0),tickets int not null default 0 check(tickets>=0),prestige int not null default 0,season_xp int not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.player_progress(user_id uuid primary key references auth.users(id) on delete cascade,unlocked_characters jsonb not null default '["vanguard","volt"]',unlocked_weapons jsonb not null default '["pulse_pistol","iron_blade"]',skill_tree jsonb not null default '{}',achievements jsonb not null default '{}',statistics jsonb not null default '{}',settings jsonb not null default '{}',daily_state jsonb not null default '{}',updated_at timestamptz not null default now());
create table if not exists public.runs(id bigint generated always as identity primary key,user_id uuid not null references public.profiles(id) on delete cascade,season int not null default 1,mode text not null,map text not null,character_id text not null,wave int not null,seconds int not null,kills int not null,level int not null,total_damage bigint not null,verified boolean not null default true,created_at timestamptz not null default now());
create index if not exists runs_leaderboard_idx on public.runs(season,wave desc,seconds desc,kills desc);
alter table public.profiles enable row level security;alter table public.player_progress enable row level security;alter table public.runs enable row level security;
drop policy if exists "profile read" on public.profiles;create policy "profile read" on public.profiles for select using(true);
drop policy if exists "profile own insert" on public.profiles;create policy "profile own insert" on public.profiles for insert with check(auth.uid()=id);
drop policy if exists "profile own update" on public.profiles;create policy "profile own update" on public.profiles for update using(auth.uid()=id) with check(auth.uid()=id);
drop policy if exists "progress own" on public.player_progress;create policy "progress own" on public.player_progress for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists "runs read" on public.runs;create policy "runs read" on public.runs for select using(true);
drop policy if exists "runs own insert" on public.runs;create policy "runs own insert" on public.runs for insert with check(auth.uid()=user_id);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into profiles(id,display_name) values(new.id,coalesce(new.raw_user_meta_data->>'display_name','ناجٍ جديد'));insert into player_progress(user_id) values(new.id);return new;end;$$;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
