"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$("#game"),ctx=canvas.getContext("2d",{alpha:false});
let W=innerWidth,H=innerHeight,dpr=Math.min(devicePixelRatio||1,2);
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
const SAVE_KEY='deepmine_save_v2';
const defaults={metaGold:0,bestWave:0,runs:0,kills:0,totalOre:0,unlockedChars:2,unlockedMaps:1,unlockedWeapons:2,achievements:[],settings:{sfx:true,music:true,shake:true,quality:'high'}};
let save=Object.assign({},defaults,JSON.parse(localStorage.getItem(SAVE_KEY)||'{}'));save.settings=Object.assign({},defaults.settings,save.settings||{});
function persist(){localStorage.setItem(SAVE_KEY,JSON.stringify(save))}
const resources=[['coal','فحم','#46545b'],['copper','نحاس','#db7c47'],['silver','فضة','#c4d6dd'],['gold','ذهب','#ffc857'],['crystal','كريستال','#63e6de'],['ruby','ياقوت','#ff5277'],['emerald','زمرد','#47dc83'],['diamond','ألماس','#8eeaff'],['mythic','نواة أسطورية','#ff8bf4']];
const weapons=[
 ['معول خشبي','⛏',1,0.78,145],['معول حجري','◆',1.25,0.72,155],['معول حديدي','✦',1.6,0.64,170],['معول ذهبي','✧',2,0.54,180],['معول ألماسي','◇',2.7,0.48,195],['مثقاب آلي','◉',1.1,0.18,215],['ليزر التعدين','⌁',3.8,0.9,310]
];
const chars=[
 ['المنقب السريع','⚡','سرعة حركة +20%','speed'],['جامع الكنوز','✦','ذهب +25% وحظ أعلى','treasure'],['سيد المتفجرات','✹','كل خامس ضربة تنفجر','boom'],['خبير الكريستال','◇','الكريستال يقوّي الضرر','crystal'],['الحفار المدرّع','⬢','دفاع +4 وصحة +25','tank'],['عين الأعماق','◎','مدى وحرج +15%','sniper'],['جامع الخردة','♻','التدوير والمتجر أرخص','scrap'],['عدّاء الأنفاق','➤','اندفاع أسرع وآمن','dash'],['كاسر الصخور','◆','ضرر الزعماء +40%','boss'],['الحفار الأسطوري','♛','كل الإحصاءات +12%','legend']
];
const maps=[['الكهف المبتدئ','أرض مستقرة وموارد متوازنة','#17343a'],['منجم الفحم','أسراب أكبر وفحم وفير','#252b2d'],['منجم الذهب','أعداء أسرع وذهب مضاعف','#3a2d16'],['كهوف الكريستال','شظايا خطرة وبلورات نادرة','#18313c'],['الأعماق السحيقة','ظلام كثيف ووحوش نخبة','#1c172d'],['نواة الأرض','حرارة قصوى وغنائم أسطورية','#3b1714']];
const upgradeDefs=[
 ['حدة المعول','ضرر +15%','damage','⚔'],['تروس سريعة','سرعة هجوم +14%','attack','◴'],['حذاء المنجم','سرعة حركة +12%','speed','➤'],['قلب صخري','صحة قصوى +20 وتعافي 20','health','♥'],['صفائح حديدية','دفاع +2','armor','⬢'],['عين الصقر','حرج +8%','crit','◎'],['ذراع طويلة','مدى +14%','range','⌁'],['مغناطيس الخام','سرعة ومدى الجمع +22%','pickup','⊙'],['بوصلة الكنوز','حظ +18%','luck','✦'],['رخصة التاجر','ذهب مكتسب +20%','gold','●']
];
const enemyTypes={
 bat:{name:'خفاش المنجم',hp:12,speed:95,size:9,color:'#a98adf',damage:7,xp:3},spider:{name:'عنكبوت الكهف',hp:22,speed:66,size:12,color:'#d76f55',damage:10,xp:5},skeleton:{name:'هيكل عامل',hp:38,speed:48,size:14,color:'#c5d0c8',damage:13,xp:8},worm:{name:'دودة الصخور',hp:62,speed:42,size:17,color:'#bd8557',damage:16,xp:11},crystal:{name:'وحش الكريستال',hp:90,speed:38,size:19,color:'#4bd6cf',damage:20,xp:15},guardian:{name:'حارس الأعماق',hp:150,speed:30,size:22,color:'#dfb354',damage:25,xp:22}
};
const bossDefs=[['ملك العناكب','#ef5e72',650,42,38],['دودة الأعماق العملاقة','#d88d48',1000,36,46],['عملاق الصخور','#9b9284',1500,28,52],['تنين الكريستال','#5fe0df',2200,48,44]];
let state='menu',game=null,selectedChar=0,selectedMap=0,last=performance.now(),keys={},pointer={active:false,x:0,y:0},audio=null,musicTimer=null,shake=0;
class Pool{constructor(factory,n){this.factory=factory;this.items=Array.from({length:n},factory)}get(){let o=this.items.find(x=>!x.active);if(!o){o=this.factory();this.items.push(o)}o.active=true;return o}each(fn){for(const o of this.items)if(o.active)fn(o)}}
const enemies=new Pool(()=>({active:false}),320),bullets=new Pool(()=>({active:false}),100),drops=new Pool(()=>({active:false}),220),particles=new Pool(()=>({active:false}),400),texts=new Pool(()=>({active:false}),100);
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));if(id)$(id).classList.add('active');state=id?id.slice(1):'playing'}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1600)}
function initAudio(){if(audio)return;audio=new (window.AudioContext||window.webkitAudioContext)();startMusic()}
function tone(freq,dur=.08,type='square',vol=.04){if(!save.settings.sfx||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}
function startMusic(){clearInterval(musicTimer);if(!audio||!save.settings.music)return;let i=0,notes=[82,98,110,123,98,73,82,65];musicTimer=setInterval(()=>{if(state==='playing'){const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=notes[i++%notes.length];g.gain.setValueAtTime(.018,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.8);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.8)}},850)}
function renderSelect(){
 $('#characterGrid').innerHTML=chars.map((c,i)=>`<article class="char-card ${i===selectedChar?'selected':''} ${i>=save.unlockedChars?'locked':''}" data-char="${i}"><span class="char-icon">${c[1]}</span><h4>${c[0]}</h4><p>${c[2]}</p></article>`).join('');
 $('#mapGrid').innerHTML=maps.map((m,i)=>`<article class="map-card ${i===selectedMap?'selected':''} ${i>=save.unlockedMaps?'locked':''}" data-map="${i}" style="background:linear-gradient(145deg,${m[2]},#0b191d)"><h4>${m[0]}</h4><p>${m[1]}</p></article>`).join('');
 $$('.char-card:not(.locked)').forEach(e=>e.onclick=()=>{selectedChar=+e.dataset.char;renderSelect()});$$('.map-card:not(.locked)').forEach(e=>e.onclick=()=>{selectedMap=+e.dataset.map;renderSelect()});
}
function newRun(){initAudio();enemies.items.forEach(x=>x.active=false);bullets.items.forEach(x=>x.active=false);drops.items.forEach(x=>x.active=false);particles.items.forEach(x=>x.active=false);texts.items.forEach(x=>x.active=false);
 const p={x:W/2,y:H/2,r:15,hp:100,maxHp:100,speed:205,damage:10,attackRate:.72,range:220,armor:0,crit:.05,pickup:95,luck:0,goldMult:1,level:1,xp:0,nextXp:25,inv:0,dash:0,weapon:0,weaponLevel:1};
 const trait=chars[selectedChar][3];if(trait==='speed')p.speed*=1.2;if(trait==='treasure'){p.goldMult=1.25;p.luck=.18}if(trait==='tank'){p.maxHp+=25;p.hp+=25;p.armor=4}if(trait==='sniper'){p.range*=1.15;p.crit=.2}if(trait==='legend')for(const k of ['speed','damage','range','maxHp'])p[k]*=1.12;
 game={p,wave:1,time:30,spawn:0,shot:0,gold:0,kills:0,damage:0,ores:Object.fromEntries(resources.map(r=>[r[0],0])),upgrades:[],weaponOwned:[0],lockedShop:[],rerolls:0,startTime:performance.now(),trait,boss:false,bossKilled:0,hitStreak:0,map:selectedMap};
 show(null);$('#hud').classList.remove('hidden');updateHud();tone(160,.2,'sawtooth');
}
function startWave(){game.wave++;game.time=30+Math.min(game.wave,10);game.boss=false;show(null);$('#hud').classList.remove('hidden');tone(180,.2,'sawtooth')}
function spawnEnemy(){const w=game.wave;let type=w<2?'bat':w<4?(Math.random()<.35?'spider':'bat'):w<7?pick(['bat','spider','skeleton']):w<11?pick(['spider','skeleton','worm']):w<16?pick(['skeleton','worm','crystal']):pick(['worm','crystal','guardian']);const d=enemyTypes[type],e=enemies.get(),side=Math.floor(Math.random()*4),pad=50;e.x=side===0?-pad:side===1?W+pad:Math.random()*W;e.y=side===2?-pad:side===3?H+pad:Math.random()*H;e.type=type;e.size=d.size;e.maxHp=d.hp*(1+w*.18)*(1+selectedMap*.11);e.hp=e.maxHp;e.speed=d.speed*(1+Math.min(w,.25*w)/45)*(1+selectedMap*.025);e.damage=d.damage*(1+w*.1);e.color=d.color;e.xp=d.xp;e.hit=0;e.boss=false}
function spawnBoss(){const b=bossDefs[Math.min(Math.floor(game.wave/5)-1,bossDefs.length-1)],e=enemies.get(),side=Math.random()<.5?-60:W+60;e.x=side;e.y=H/2;e.type='boss';e.name=b[0];e.color=b[1];e.maxHp=b[2]*(1+game.wave*.16);e.hp=e.maxHp;e.speed=b[3];e.size=b[4];e.damage=30+game.wave*2;e.xp=140;e.hit=0;e.boss=true;game.boss=true;toast('⚠ '+b[0]+' يقترب');tone(65,.8,'sawtooth',.08)}
function shoot(){const p=game.p;let target=null,dist=p.range;enemies.each(e=>{const d=Math.hypot(e.x-p.x,e.y-p.y);if(d<dist){dist=d;target=e}});if(!target)return;const a=Math.atan2(target.y-p.y,target.x-p.x),w=weapons[p.weapon],b=bullets.get();b.x=p.x;b.y=p.y;b.vx=Math.cos(a)*(430+w[4]);b.vy=Math.sin(a)*(430+w[4]);b.damage=p.damage*w[2]*(1+(p.weaponLevel-1)*.22);b.life=1;b.r=p.weapon===6?5:4;b.color=p.weapon>=4?'#7ff3ee':'#ffc857';game.hitStreak++;tone(p.weapon===6?520:260,.035,'square',.018)}
function damageEnemy(e,dmg){let crit=Math.random()<game.p.crit;if(crit)dmg*=2;if(game.trait==='boss'&&e.boss)dmg*=1.4;if(game.trait==='crystal')dmg*=1+Math.min(game.ores.crystal*.015,.6);e.hp-=dmg;e.hit=.08;game.damage+=dmg;floatText(e.x,e.y-Math.max(12,e.size),Math.round(dmg)+(crit?'!':''),crit?'#ffc857':'#e8faf5');burst(e.x,e.y,e.color,crit?7:3);if(game.trait==='boom'&&game.hitStreak%5===0)enemies.each(x=>{if(x!==e&&Math.hypot(x.x-e.x,x.y-e.y)<80)x.hp-=dmg*.65});if(e.hp<=0)killEnemy(e)}
function killEnemy(e){e.active=false;game.kills++;if(e.boss){game.bossKilled++;game.gold+=45+game.wave*4;for(let i=0;i<12;i++)makeDrop(e.x+rand(-30,30),e.y+rand(-30,30),true);tone(90,.5,'sawtooth',.08);shake=14}else{if(Math.random()<.82)makeDrop(e.x,e.y,false);if(Math.random()<.16+game.p.luck)game.gold+=Math.ceil((1+game.wave*.1)*game.p.goldMult)}gainXp(e.xp);burst(e.x,e.y,e.color,e.boss?35:8)}
function makeDrop(x,y,rare){const d=drops.get(),luck=game.p.luck+selectedMap*.035,r=Math.random();let idx=rare?Math.min(8,3+Math.floor(Math.random()*6)):r<.48?0:r<.7?1:r<.84?2:r<.93?3:r<.97+luck*.05?4:Math.min(8,5+Math.floor(Math.random()*4));d.x=x;d.y=y;d.type=idx;d.life=18;d.r=rare?6:4}
function gainXp(n){const p=game.p;p.xp+=n;while(p.xp>=p.nextXp){p.xp-=p.nextXp;p.level++;p.nextXp=Math.floor(24+p.level*11);game.pendingLevels=(game.pendingLevels||0)+1}}
function applyUpgrade(key){const p=game.p;({damage:()=>p.damage*=1.15,attack:()=>p.attackRate*=.86,speed:()=>p.speed*=1.12,health:()=>{p.maxHp+=20;p.hp=Math.min(p.maxHp,p.hp+20)},armor:()=>p.armor+=2,crit:()=>p.crit+=.08,range:()=>p.range*=1.14,pickup:()=>p.pickup*=1.22,luck:()=>p.luck+=.18,gold:()=>p.goldMult+=.2})[key]();game.upgrades.push(key);game.pendingLevels--;if(game.pendingLevels>0)setTimeout(showUpgrades,100);else show(null)}
function showUpgrades(){state='choice';show('#choice');const opts=shuffle([...upgradeDefs]).slice(0,3);$('#upgradeChoices').innerHTML=opts.map((u,i)=>`<button class="choice-card" data-i="${i}"><span class="ico">${u[3]}</span><h4>${u[0]}</h4><p>${u[1]}</p></button>`).join('');$$('.choice-card').forEach(e=>e.onclick=()=>applyUpgrade(opts[+e.dataset.i][2]));tone(600,.12,'sine')}
function endWave(){enemies.items.forEach(e=>e.active=false);bullets.items.forEach(e=>e.active=false);game.gold+=8+game.wave*2;showShop()}
function rarity(){const r=Math.random()+game.p.luck*.15;return r>.96?4:r>.82?3:r>.58?2:r>.28?1:0}
const rarities=[['عادي',''],['غير شائع','uncommon'],['نادر','rare'],['ملحمي','epic'],['أسطوري','legendary']];
function shopRoll(){let arr=[];for(let i=0;i<3;i++){const wi=Math.min(save.unlockedWeapons-1,Math.floor(Math.random()*save.unlockedWeapons)),r=rarity(),cost=Math.round((12+wi*7+game.wave*1.5)*(1+r*.55));arr.push({wi,r,cost,locked:game.lockedShop[i]||false,sold:false})}game.shop=arr;renderShop()}
function showShop(){show('#shop');state='shop';$('#hud').classList.add('hidden');shopRoll()}
function renderShop(){const s=game.shop;$('#shopGold').textContent=Math.floor(game.gold);$('#rerollCost').textContent=5+game.rerolls*3;$('#shopItems').innerHTML=s.map((it,i)=>{const w=weapons[it.wi],ra=rarities[it.r];return `<article class="shop-card ${it.sold?'sold':''}"><button class="lock-btn" data-lock="${i}">${it.locked?'🔒':'○'}</button><span class="ico">${w[1]}</span><h4>${w[0]}</h4><p>ضرر ×${(w[2]*(1+it.r*.16)).toFixed(1)} · سرعة ${w[3]}ث</p><p class="rarity ${ra[1]}">${ra[0]}</p><button data-buy="${i}"><span class="coin">●</span> ${it.cost}</button></article>`}).join('');$$('[data-buy]').forEach(e=>e.onclick=()=>buyItem(+e.dataset.buy));$$('[data-lock]').forEach(e=>e.onclick=()=>{const i=+e.dataset.lock;s[i].locked=!s[i].locked;game.lockedShop[i]=s[i].locked;renderShop()})}
function buyItem(i){const it=game.shop[i];if(it.sold||game.gold<it.cost){tone(80,.1);return}game.gold-=it.cost;it.sold=true;if(game.weaponOwned.includes(it.wi)){game.p.weaponLevel++;toast('تم تطوير '+weapons[it.wi][0])}else{game.weaponOwned.push(it.wi);game.p.weapon=it.wi;toast('تم تجهيز '+weapons[it.wi][0])}game.p.damage*=1+it.r*.045;renderShop();tone(700,.12,'sine')}
function recycle(){if(game.weaponOwned.length<=1){toast('لا يوجد سلاح زائد');return}const old=game.weaponOwned.shift();game.gold+=8+old*4;toast('تم تدوير '+weapons[old][0]);renderShop()}
function update(dt){if(state!=='playing'||!game)return;const p=game.p;game.time-=dt;if(game.time<=0){endWave();return}if(game.wave%5===0&&!game.boss&&!enemies.items.some(e=>e.active&&e.boss))spawnBoss();game.spawn-=dt;const rate=Math.max(.055,.56-game.wave*.025-selectedMap*.018);if(game.spawn<=0){game.spawn=rate;const count=1+Math.floor(game.wave/9);for(let i=0;i<count;i++)spawnEnemy()}
 let dx=(keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0),dy=(keys.ArrowDown||keys.KeyS?1:0)-(keys.ArrowUp||keys.KeyW?1:0);if(pointer.active){dx=pointer.x;dy=pointer.y}const len=Math.hypot(dx,dy)||1;p.x=Math.max(18,Math.min(W-18,p.x+dx/len*p.speed*dt));p.y=Math.max(18,Math.min(H-18,p.y+dy/len*p.speed*dt));p.inv-=dt;p.dash-=dt;
 game.shot-=dt;if(game.shot<=0){game.shot=p.attackRate*weapons[p.weapon][3];shoot()}
 enemies.each(e=>{const a=Math.atan2(p.y-e.y,p.x-e.x);e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt;e.hit-=dt;const d=Math.hypot(e.x-p.x,e.y-p.y);if(d<e.size+p.r&&p.inv<=0){const taken=Math.max(1,e.damage-p.armor);p.hp-=taken;p.inv=.65;shake=save.settings.shake?8:0;floatText(p.x,p.y-25,'-'+Math.round(taken),'#ff6875');tone(110,.12,'sawtooth',.06);if(p.hp<=0)gameOver()}});
 bullets.each(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life<=0||b.x<0||b.x>W||b.y<0||b.y>H){b.active=false;return}enemies.each(e=>{if(b.active&&Math.hypot(b.x-e.x,b.y-e.y)<b.r+e.size){damageEnemy(e,b.damage);b.active=false}})});
 drops.each(d=>{d.life-=dt;if(d.life<=0){d.active=false;return}let dd=Math.hypot(p.x-d.x,p.y-d.y);if(dd<p.pickup){const a=Math.atan2(p.y-d.y,p.x-d.x),spd=80+(p.pickup-dd)*5;d.x+=Math.cos(a)*spd*dt;d.y+=Math.sin(a)*spd*dt}if(dd<p.r+8){const key=resources[d.type][0];game.ores[key]++;d.active=false;tone(380+d.type*35,.035,'sine',.015)}});
 particles.each(q=>{q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt;q.vx*=.96;q.vy*=.96;if(q.life<=0)q.active=false});texts.each(t=>{t.y-=28*dt;t.life-=dt;if(t.life<=0)t.active=false});if(game.pendingLevels>0)showUpgrades();updateHud()}
function dash(){if(!game||game.p.dash>0)return;let dx=(keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0),dy=(keys.ArrowDown||keys.KeyS?1:0)-(keys.ArrowUp||keys.KeyW?1:0);if(pointer.active){dx=pointer.x;dy=pointer.y}if(!dx&&!dy)dy=-1;const l=Math.hypot(dx,dy);game.p.x=Math.max(20,Math.min(W-20,game.p.x+dx/l*105));game.p.y=Math.max(20,Math.min(H-20,game.p.y+dy/l*105));game.p.inv=.35;game.p.dash=game.trait==='dash'?1.1:2.4;burst(game.p.x,game.p.y,'#51e5c2',15);tone(220,.12,'sawtooth')}
function updateHud(){if(!game)return;const p=game.p;$('#waveNum').textContent=game.wave;$('#timer').textContent='00:'+String(Math.max(0,Math.ceil(game.time))).padStart(2,'0');$('#gold').textContent=Math.floor(game.gold);$('#hpFill').style.width=Math.max(0,p.hp/p.maxHp*100)+'%';$('#hpText').textContent=`${Math.ceil(p.hp)} / ${Math.round(p.maxHp)}`;$('#xpFill').style.width=p.xp/p.nextXp*100+'%';$('#xpText').textContent='المستوى '+p.level;$('#resourceHud').innerHTML=resources.filter(r=>game.ores[r[0]]).map(r=>`<span style="color:${r[2]}">◆ ${r[1]} ${game.ores[r[0]]}</span>`).join('')}
function gameOver(){if(!game||state==='results')return;state='results';$('#hud').classList.add('hidden');save.metaGold+=Math.floor(game.gold);save.bestWave=Math.max(save.bestWave,game.wave);save.runs++;save.kills+=game.kills;const oreTotal=Object.values(game.ores).reduce((a,b)=>a+b,0);save.totalOre+=oreTotal;const unlocks=[];if(save.bestWave>=3&&save.unlockedChars<3){save.unlockedChars=3;unlocks.push(chars[2][0])}if(save.bestWave>=5&&save.unlockedMaps<2){save.unlockedMaps=2;save.unlockedWeapons=Math.max(3,save.unlockedWeapons);unlocks.push(maps[1][0])}if(save.bestWave>=10){save.unlockedChars=Math.max(5,save.unlockedChars);save.unlockedMaps=Math.max(3,save.unlockedMaps);save.unlockedWeapons=Math.max(5,save.unlockedWeapons)}if(save.bestWave>=15){save.unlockedChars=Math.max(8,save.unlockedChars);save.unlockedMaps=Math.max(5,save.unlockedMaps);save.unlockedWeapons=Math.max(7,save.unlockedWeapons)}if(save.bestWave>=20){save.unlockedChars=10;save.unlockedMaps=6}checkAchievements();persist();showResults(unlocks)}
function showResults(unlocks){show('#results');$('#resultWave').textContent='بلغت الموجة '+game.wave;const mins=Math.floor((performance.now()-game.startTime)/60000),secs=Math.floor((performance.now()-game.startTime)/1000)%60;$('#statsGrid').innerHTML=[['الموجة',game.wave],['الأعداء',game.kills],['الضرر',Math.round(game.damage).toLocaleString()],['الوقت',`${mins}:${String(secs).padStart(2,'0')}`]].map(x=>`<div class="stat"><b>${x[1]}</b><small>${x[0]}</small></div>`).join('');$('#resultResources').innerHTML=resources.filter(r=>game.ores[r[0]]).map(r=>`<span style="color:${r[2]}">◆ ${r[1]} ${game.ores[r[0]]}</span>`).join('')||'<span>لا شيء</span>';$('#newUnlocks').innerHTML=unlocks.length?`<div class="achievement">فتح جديد: ${unlocks.join('، ')}</div>`:'';tone(90,.6,'triangle',.05)}
const achievements=[['first','الخطوة الأولى','أكمل رحلة واحدة',s=>s.runs>=1],['slayer','منظف الأنفاق','اهزم 500 عدو',s=>s.kills>=500],['rich','حمّى الذهب','اجمع 1000 ذهب دائم',s=>s.metaGold>=1000],['deep','لا تخشَ الظلام','بلغ الموجة 10',s=>s.bestWave>=10],['ore','خبير المعادن','استخرج 500 مورد',s=>s.totalOre>=500]];
function checkAchievements(){for(const a of achievements)if(!save.achievements.includes(a[0])&&a[3](save)){save.achievements.push(a[0]);save.metaGold+=50;toast('إنجاز: '+a[1])}}
function renderCodex(){checkAchievements();persist();$('#codexContent').innerHTML=`<div class="stats-grid"><div class="stat"><b>${save.bestWave}</b><small>أفضل موجة</small></div><div class="stat"><b>${save.runs}</b><small>رحلات</small></div><div class="stat"><b>${save.kills}</b><small>إقصاءات</small></div><div class="stat"><b>${save.totalOre}</b><small>موارد</small></div></div><h3>الإنجازات</h3>${achievements.map(a=>`<div class="achievement ${save.achievements.includes(a[0])?'':'locked-ach'}"><b>${a[1]}</b><small> · ${a[2]}</small></div>`).join('')}<h3>الترسانة</h3><div class="card-grid">${weapons.map((w,i)=>`<div class="char-card ${i>=save.unlockedWeapons?'locked':''}"><span class="char-icon">${w[1]}</span><h4>${w[0]}</h4><p>قوة ${w[2]} · مدى ${w[4]}</p></div>`).join('')}</div>`}
function floatText(x,y,text,color){const t=texts.get();Object.assign(t,{x,y,text,color,life:.65})}function burst(x,y,color,n){if(save.settings.quality==='low')n=Math.ceil(n/2);for(let i=0;i<n;i++){const p=particles.get(),a=Math.random()*Math.PI*2,s=rand(20,130);Object.assign(p,{x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rand(.2,.6),color,r:rand(1,3)})}}
function draw(){ctx.save();if(shake>0){ctx.translate(rand(-shake,shake),rand(-shake,shake));shake*=.84;if(shake<.5)shake=0}const map=maps[game?.map||0],bg=map[2];ctx.fillStyle=bg;ctx.fillRect(-20,-20,W+40,H+40);drawGround();drops.each(d=>{ctx.fillStyle=resources[d.type][2];ctx.shadowBlur=10;ctx.shadowColor=ctx.fillStyle;poly(d.x,d.y,d.r,5,performance.now()/800);ctx.shadowBlur=0});particles.each(p=>{ctx.globalAlpha=Math.max(0,p.life*2);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.r,p.r);ctx.globalAlpha=1});enemies.each(drawEnemy);bullets.each(b=>{ctx.fillStyle=b.color;ctx.shadowBlur=8;ctx.shadowColor=b.color;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,7);ctx.fill();ctx.shadowBlur=0});if(game)drawPlayer();texts.each(t=>{ctx.fillStyle=t.color;ctx.font='bold 14px Tahoma';ctx.textAlign='center';ctx.fillText(t.text,t.x,t.y)});ctx.restore()}
function drawGround(){ctx.strokeStyle='#ffffff08';ctx.lineWidth=1;const step=72;for(let x=0;x<W;x+=step){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x+30,H);ctx.stroke()}for(let y=0;y<H;y+=step){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y+20);ctx.stroke()}ctx.fillStyle='#ffffff09';for(let i=0;i<30;i++){const x=(i*197)%W,y=(i*113)%H;ctx.fillRect(x,y,2,2)}}
function drawEnemy(e){ctx.save();ctx.translate(e.x,e.y);if(e.hit>0)ctx.globalAlpha=.55;ctx.fillStyle='#0005';ctx.beginPath();ctx.ellipse(2,e.size*.75,e.size*.9,e.size*.35,0,0,7);ctx.fill();ctx.fillStyle=e.hit>0?'#fff':e.color;if(e.boss){poly(0,0,e.size,7,performance.now()/1200);ctx.fillStyle='#071319';ctx.beginPath();ctx.arc(-e.size*.25,-4,4,0,7);ctx.arc(e.size*.25,-4,4,0,7);ctx.fill();ctx.fillStyle='#ff5464';ctx.fillRect(-e.size,-e.size-13,e.size*2,5);ctx.fillStyle='#51e5c2';ctx.fillRect(-e.size,-e.size-13,e.size*2*Math.max(0,e.hp/e.maxHp),5)}else if(e.type==='bat'){ctx.beginPath();ctx.moveTo(0,3);ctx.lineTo(-e.size*1.5,-6);ctx.lineTo(-e.size,7);ctx.lineTo(0,2);ctx.lineTo(e.size,-7);ctx.lineTo(e.size*1.5,6);ctx.fill()}else if(e.type==='spider'){ctx.beginPath();ctx.arc(0,0,e.size*.65,0,7);ctx.fill();ctx.strokeStyle=e.color;ctx.lineWidth=3;for(let i=-1;i<=1;i+=2)for(let j=-1;j<=1;j+=2){ctx.beginPath();ctx.moveTo(i*5,j*3);ctx.lineTo(i*e.size*1.25,j*e.size*.7);ctx.stroke()}}else{poly(0,0,e.size,e.type==='crystal'?5:6,.2)}ctx.restore()}
function drawPlayer(){const p=game.p;ctx.save();ctx.translate(p.x,p.y);if(p.inv>0&&Math.floor(p.inv*14)%2)ctx.globalAlpha=.35;ctx.fillStyle='#0007';ctx.beginPath();ctx.ellipse(2,12,15,7,0,0,7);ctx.fill();ctx.fillStyle='#e6b778';ctx.beginPath();ctx.arc(0,-2,12,0,7);ctx.fill();ctx.fillStyle='#f0c94f';ctx.beginPath();ctx.arc(0,-5,15,Math.PI,0);ctx.fill();ctx.fillRect(-15,-5,30,5);ctx.fillStyle='#16383f';ctx.fillRect(-8,0,16,14);ctx.fillStyle='#51e5c2';ctx.fillRect(-4,3,8,4);ctx.strokeStyle='#dce9e5';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(9,1);ctx.lineTo(20,-10);ctx.lineTo(26,-6);ctx.stroke();ctx.restore()}
function poly(x,y,r,n,rot=0){ctx.beginPath();for(let i=0;i<n;i++){const a=i/n*Math.PI*2+rot,px=x+Math.cos(a)*r,py=y+Math.sin(a)*r;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath();ctx.fill()}
function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
function rand(a,b){return a+Math.random()*(b-a)}function pick(a){return a[Math.floor(Math.random()*a.length)]}function shuffle(a){for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Space')dash();if(e.code==='Escape'&&state==='playing')pauseGame()});addEventListener('keyup',e=>keys[e.code]=false);
const joy=$('#joystick'),knob=joy.querySelector('i');function joyMove(e){const r=joy.getBoundingClientRect(),t=e.touches?e.touches[0]:e,x=t.clientX-(r.left+r.width/2),y=t.clientY-(r.top+r.height/2),l=Math.hypot(x,y),m=Math.min(l,38);pointer={active:true,x:x/(l||1),y:y/(l||1)};knob.style.transform=`translate(${pointer.x*m}px,${pointer.y*m}px)`}joy.addEventListener('pointerdown',e=>{joy.setPointerCapture(e.pointerId);joyMove(e)});joy.addEventListener('pointermove',e=>{if(e.buttons)joyMove(e)});joy.addEventListener('pointerup',()=>{pointer.active=false;knob.style.transform=''})
function pauseGame(){show('#pause');state='pause'}
$('#playBtn').onclick=()=>{renderSelect();show('#select')};$('#startBtn').onclick=newRun;$('#codexBtn').onclick=()=>{renderCodex();show('#codex')};$('#settingsBtn').onclick=()=>show('#settings');$$('.back').forEach(b=>b.onclick=()=>show('#menu'));$('#pauseBtn').onclick=pauseGame;$('#resumeBtn').onclick=()=>show(null);$('#quitBtn').onclick=gameOver;$('#dashBtn').onclick=dash;$('#nextWaveBtn').onclick=startWave;$('#recycleBtn').onclick=recycle;$('#rerollBtn').onclick=()=>{const c=5+game.rerolls*3;if(game.gold<c)return toast('ذهب غير كافٍ');game.gold-=c;game.rerolls++;shopRoll()};$('#againBtn').onclick=()=>{renderSelect();show('#select')};$('#homeBtn').onclick=()=>{show('#menu');refreshMenu()};
$('#sfxToggle').checked=save.settings.sfx;$('#musicToggle').checked=save.settings.music;$('#shakeToggle').checked=save.settings.shake;$('#qualitySelect').value=save.settings.quality;$('#sfxToggle').onchange=e=>{save.settings.sfx=e.target.checked;persist()};$('#musicToggle').onchange=e=>{save.settings.music=e.target.checked;persist();startMusic()};$('#shakeToggle').onchange=e=>{save.settings.shake=e.target.checked;persist()};$('#qualitySelect').onchange=e=>{save.settings.quality=e.target.value;persist()};$('#resetBtn').onclick=()=>{if(confirm('هل تريد مسح كل التقدم؟')){save=structuredClone(defaults);persist();location.reload()}};
function refreshMenu(){$('#metaGold').textContent=save.metaGold;$('#bestWave').textContent=save.bestWave}refreshMenu();
