export const CHARACTERS=[
 {id:'vanguard',name:'الطليعي',icon:'⬢',skill:'درع الصدمة',positive:'+25 صحة وصدمة كل 8 ثوانٍ',negative:'-10% سرعة',color:'#55e6c1',stats:{hp:25,speed:-.1},pulse:true},
 {id:'volt',name:'فولت',icon:'ϟ',skill:'سلسلة البرق',positive:'كل ضربة خامسة تقفز لعدوين',negative:'-15% ضرر جسدي',color:'#69b7ff',stats:{element:.2},chain:true},
 {id:'ember',name:'جمرة',icon:'✹',skill:'احتراق أبدي',positive:'النار تستمر 3 ثوانٍ',negative:'-12% صحة',color:'#ff775d',stats:{hp:-12},burn:true},
 {id:'frost',name:'حارسة الجليد',icon:'❄',skill:'تجميد شامل',positive:'تبطيء الأعداء 20%',negative:'-8% سرعة هجوم',color:'#8ce8ff',stats:{attack:-.08},slow:true},
 {id:'toxin',name:'الكيميائي',icon:'☣',skill:'وباء متسلسل',positive:'السم ينتقل عند الموت',negative:'-2 درع',color:'#8ce65d',stats:{armor:-2},poison:true},
 {id:'shade',name:'الظل',icon:'◒',skill:'خطوة الفراغ',positive:'+18% حرج ومراوغة',negative:'-20 صحة',color:'#ad82ff',stats:{crit:.18,hp:-20},evade:.12},
 {id:'titan',name:'العملاق',icon:'⬣',skill:'غضب الإصابة',positive:'+55 صحة و5 درع',negative:'-22% سرعة',color:'#d9b36c',stats:{hp:55,armor:5,speed:-.22}},
 {id:'ranger',name:'حارس الأفق',icon:'➶',skill:'طلقة ثاقبة',positive:'+30% مدى وسرعة مقذوف',negative:'-18% ضرر قريب',color:'#6ce6a3',stats:{range:.3,projectile:.2}},
 {id:'engineer',name:'المهندسة',icon:'⚙',skill:'برج آلي',positive:'برج يطلق كل ثانيتين',negative:'-10% سرعة حركة',color:'#ffd15a',stats:{speed:-.1},turret:true},
 {id:'medic',name:'المسعفة',icon:'✚',skill:'نبضة علاج',positive:'+3 تجدد صحة',negative:'-15% ضرر',color:'#ff799b',stats:{regen:3,damage:-.15}},
 {id:'berserker',name:'الهائج',icon:'⚔',skill:'هياج الدم',positive:'يزداد الضرر مع نقص الصحة',negative:'لا يتجدد تلقائياً',color:'#ff4f5e',stats:{regen:-99},rage:true},
 {id:'orbiter',name:'سيدة المدار',icon:'◎',skill:'أقمار حارسة',positive:'سلاحان يدوران حولك',negative:'-20% مدى',color:'#e593ff',stats:{range:-.2},orbits:2},
 {id:'miner',name:'منقّب الصدع',icon:'◆',skill:'حمّى الموارد',positive:'+35% عملات وجذب',negative:'-10% ضرر',color:'#ffc85a',stats:{income:.35,pickup:.3,damage:-.1}},
 {id:'rocket',name:'قائد الصواريخ',icon:'▲',skill:'وابل مداري',positive:'انفجار كل 7 إصابات',negative:'-15% سرعة هجوم',color:'#ff9d5c',stats:{attack:-.15},explosive:true},
 {id:'samurai',name:'نصل الفجر',icon:'〆',skill:'قطع خاطف',positive:'+40% ضرر قريب',negative:'-30% مدى',color:'#f4e3c1',stats:{melee:.4,range:-.3}},
 {id:'chrono',name:'ناسج الزمن',icon:'◴',skill:'كسر الزمن',positive:'تباطؤ العالم كل 12 ثانية',negative:'-15 صحة',color:'#67d8dc',stats:{hp:-15},chrono:true},
 {id:'gambler',name:'المقامر',icon:'♢',skill:'حظ متقلب',positive:'+40% حظ وندرات',negative:'الضرر يتذبذب',color:'#f2c65a',stats:{luck:.4},variance:true},
 {id:'summoner',name:'مستدعي الشظايا',icon:'♜',skill:'رفيق صدع',positive:'مخلوق يقاتل بجانبك',negative:'-20% ضرر مباشر',color:'#ca8cff',stats:{damage:-.2},pet:true},
 {id:'phoenix',name:'العنقاء',icon:'♨',skill:'عودة واحدة',positive:'تعود بنصف الصحة مرة',negative:'-25% درع',color:'#ff684f',stats:{armor:-.25},revive:true},
 {id:'null',name:'صفر',icon:'∅',skill:'محو الواقع',positive:'+12% لكل الإحصاءات',negative:'تطورات أقل جودة',color:'#f2f7ff',stats:{all:.12},secret:true}
];
export const WEAPONS=[
 ['pulse_pistol','مسدس نبضي','ranged','kinetic',12,.52,390,1],['iron_blade','نصل حديدي','melee','kinetic',24,.72,92,1],['arc_coil','ملف الصاعقة','ranged','electric',10,.68,330,3],['flame_caster','قاذف اللهب','ranged','fire',7,.14,225,1],['frost_lance','رمح الصقيع','ranged','ice',19,.9,420,1],['toxin_sprayer','بخاخ السم','ranged','poison',5,.12,210,1],['rocket_tube','قاذف الصواريخ','ranged','explosive',48,1.45,480,1],['beam_array','مصفوفة الليزر','ranged','laser',16,.2,560,1],['storm_hammer','مطرقة العاصفة','melee','electric',40,1.05,105,1],['ember_sword','سيف الجمر','melee','fire',31,.66,100,1],['glacier_axe','فأس الجليد','melee','ice',44,1.1,112,1],['venom_fang','ناب السم','melee','poison',20,.44,85,1],['scattergun','بندقية مبعثرة','ranged','kinetic',9,.9,280,6],['railgun','مدفع سككي','ranged','laser',75,1.8,650,1],['tesla_orb','كرة تسلا','orbit','electric',18,.6,80,2],['saw_drone','منشار مسيّر','orbit','kinetic',25,.35,72,2],['meteor_core','نواة النيزك','ranged','fire',90,2.2,520,1],['absolute_zero','الصفر المطلق','ranged','ice',58,1.7,500,4],['plague_engine','محرك الطاعون','ranged','poison',15,.32,380,3],['sunbreaker','كاسر الشمس','ranged','legendary',135,2.5,700,1]
].map(([id,name,type,element,damage,cooldown,range,count])=>({id,name,type,element,damage,cooldown,range,count}));
export const MAPS=[['desert','بحر الرماد','#b56d43','رياح تزيد سرعة المقذوفات'],['ice','القفر المتجمد','#4a86a8','بقع جليدية متحركة'],['forest','الغابة الطافرة','#397058','جذور تستدعي أسراباً'],['volcano','فوهة الغضب','#963e32','حمم دورية'],['city','المدينة المهدمة','#525a6d','ممرات وحواجز'],['lab','المختبر السري','#4a477b','أعداء متحوّلون']].map(([id,name,color,rule])=>({id,name,color,rule}));
export const MODES=[['normal','عادي',1,1],['hard','صعب',1.35,1.25],['nightmare','كابوس',1.8,1.6],['endless','لا نهائي',1.25,1.4],['hardcore','Hardcore',2,2],['bossrush','Boss Rush',1.7,2.2]].map(([id,name,difficulty,reward])=>({id,name,difficulty,reward}));
export const UPGRADES=[
 ['damage','قوة الصدع','الضرر +12%','⚔'],['attack','مسرّع زمني','سرعة الهجوم +10%','◴'],['health','نواة حيوية','الصحة +18 وتعافي','♥'],['speed','أحذية الطيف','السرعة +10%','➤'],['armor','نسيج تيتانيوم','الدرع +2','⬢'],['crit','عدسة قاتلة','الحرج +7%','◎'],['range','محدد بعيد','المدى +12%','⌁'],['pickup','مغناطيس كمي','الجذب +25%','⊙'],['regen','ترميم خلوي','التجدد +1.2','✚'],['luck','نرد الصدع','الحظ +12%','♢'],['projectiles','نسخة مقذوف','مقذوف إضافي','✦'],['pierce','اختراق','اختراق عدو إضافي','➶']
].map(([id,name,desc,icon])=>({id,name,desc,icon}));
const affixes=[['الحاد',{damage:.08}],['السريع',{attack:.07}],['الحيوي',{hp:12}],['المحصّن',{armor:1}],['المبارك',{luck:.08}],['المغناطيسي',{pickup:.12}],['العدّاء',{speed:.06}],['الناقد',{crit:.045}],['المتجدد',{regen:.5}],['البعيد',{range:.08}]];
const bases=['مفاعل','خاتم','قناع','حذاء','قلب','عدسة','شريحة','درع','تميمة','قفاز','نواة','حزام','منارة','وشاح','خوذة'];
export const ITEMS=Array.from({length:150},(_,i)=>{const a=affixes[i%affixes.length],tier=Math.floor(i/50)+1,penalty=affixes[(i+4)%affixes.length];return{id:`item_${i+1}`,name:`${bases[i%bases.length]} ${a[0]}`,tier,price:18+tier*16+(i%15)*3,bonus:Object.fromEntries(Object.entries(a[1]).map(([k,v])=>[k,v*tier])),penalty:i%3===0?Object.fromEntries(Object.entries(penalty[1]).map(([k,v])=>[k,-v*.35*tier])):{}}});
const enemyFamilies=[['ساعي الظل','chaser'],['عين الصدع','shooter'],['قنبلة حية','exploder'],['ناسج السرب','summoner'],['مجمّد الروح','slower'],['حارس مدرّع','tank'],['طيف خاطف','dasher'],['ملتَهِم','leech'],['منشطر','splitter'],['محوّر','mutant']];
export const ENEMIES=Array.from({length:50},(_,i)=>{const family=enemyFamilies[i%10],tier=Math.floor(i/10)+1;return{id:`enemy_${i+1}`,name:`${family[0]} ${tier}`,behavior:family[1],tier,hp:8*tier*(1+(i%5)*.25),speed:38+(i%7)*7,damage:3+tier*2,size:9+tier*2,color:`hsl(${(i*47)%360} 65% ${48+tier*3}%)`,xp:2+tier*2}});
export const ACHIEVEMENTS=Array.from({length:100},(_,i)=>{const types=['kills','wave','damage','runs','level'],type=types[i%5],step=Math.floor(i/5)+1,target=type==='kills'?step*250:type==='wave'?step*3:type==='damage'?step*25000:type==='runs'?step*5:step*4;return{id:`achievement_${i+1}`,name:['صائد','ناجٍ','مدمّر','رحّالة','متفوّق'][i%5]+` ${step}`,type,target,reward:{gold:50+step*15,gems:step%5===0?5:0}}});
export const SKILLS=[['damage','الضرر',.03,100],['health','الصحة',5,100],['speed','السرعة',.02,120],['luck','الحظ',.025,140],['pickup','جمع الموارد',.04,110],['crit','الضربات الحرجة',.02,150],['armor','مقاومة الضرر',1,180]].map(([id,name,value,cost])=>({id,name,value,cost,max:20}));
